import {
  CompanyProfile,
  UserProfile,
  Warehouse,
  Product,
  Customer,
  Supplier,
  SalesInvoice,
  DeliveryChallan,
  PurchaseInvoice,
  Payment,
  Expense,
  InventoryTransaction,
  AuditLog,
  NotificationItem,
  UserRole,
  Permission,
} from '@/types';

export const INITIAL_COMPANY: CompanyProfile = {
  id: 'comp-101',
  name: 'Zenith Apex Technologies Pvt Ltd',
  legal_name: 'Zenith Apex Technologies Private Limited',
  logo_url: '',
  address: 'Plot 44, Electronic City Phase 1, Hosur Main Road',
  city: 'Bengaluru',
  state: 'Karnataka',
  state_code: '29',
  country: 'India',
  pin_code: '560100',
  phone: '+91 80 4123 8899',
  email: 'accounts@zenithapex.in',
  website: 'https://zenithapex.in',
  gstin: '29ABCDE1234F1Z5',
  pan: 'ABCDE1234F',
  cin: 'U72200KA2021PTC145892',
  bank_name: 'HDFC Bank Ltd',
  account_number: '50200088991234',
  ifsc: 'HDFC0000128',
  branch: 'Koramangala 4th Block, Bengaluru',
  upi_id: 'zenithapex@hdfcbank',
  upi_payee_name: 'Zenith Apex Technologies Pvt Ltd',
  merchant_code: '5411',
  invoice_prefix: 'INV-2627-',
  challan_prefix: 'DC-2627-',
  purchase_prefix: 'PO-2627-',
  currency: 'INR',
  allow_negative_inventory: false,
  default_gst_rate: 18,
};

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-1',
    company_id: 'comp-101',
    name: 'Central Distribution Center (BLR)',
    code: 'CDC-01',
    address: 'Warehouse Complex #4, Peenya Industrial Area, Bengaluru',
    contact_person: 'Ramesh Kulkarni',
    phone: '+91 98450 11223',
    is_default: true,
    status: 'active',
  },
  {
    id: 'wh-2',
    company_id: 'comp-101',
    name: 'Mumbai Regional Depot',
    code: 'MRD-02',
    address: 'Gala 12, Bhiwandi Logistics Park, Thane, Mumbai',
    contact_person: 'Vikas Deshmukh',
    phone: '+91 98200 44556',
    is_default: false,
    status: 'active',
  },
  {
    id: 'wh-3',
    company_id: 'comp-101',
    name: 'Delhi NCR Hub',
    code: 'DCR-03',
    address: 'Sector 37, Pace City II, Gurugram, Haryana',
    contact_person: 'Amit Sharma',
    phone: '+91 99100 77889',
    is_default: false,
    status: 'active',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'usr-1',
    email: 'vikram.admin@zenithapex.in',
    full_name: 'Vikram Kumar (Super Admin)',
    role: 'Super Admin',
    permissions: [
      'view_dashboard',
      'view_sales', 'create_sales', 'edit_sales', 'delete_sales', 'manage_challans',
      'view_purchases', 'create_purchases', 'edit_purchases', 'delete_purchases',
      'view_products', 'create_products', 'edit_products', 'delete_products', 'manage_inventory',
      'view_customers', 'create_customers', 'edit_customers', 'delete_customers',
      'view_suppliers', 'create_suppliers', 'edit_suppliers', 'delete_suppliers',
      'manage_payments', 'manage_expenses', 'view_accounting',
      'view_reports', 'manage_users', 'manage_settings', 'view_audit_logs', 'manage_database',
    ],
    status: 'active',
    company_id: 'comp-101',
    phone: '+91 98450 99887',
    created_at: '2026-01-15T10:00:00Z',
    last_login_at: '2026-09-25T11:45:00Z',
    email_verified: true,
    password: 'password123',
  },
  {
    id: 'usr-2',
    email: 'priya.sharma@zenithapex.in',
    full_name: 'Priya Sharma (Senior Accountant)',
    role: 'Accountant',
    permissions: [
      'view_dashboard',
      'view_sales', 'create_sales', 'edit_sales', 'manage_challans',
      'view_customers', 'create_customers', 'edit_customers',
      'view_purchases', 'create_purchases', 'edit_purchases',
      'view_suppliers', 'create_suppliers',
      'view_products', 'manage_inventory',
      'manage_payments', 'manage_expenses', 'view_accounting',
      'view_reports',
    ],
    status: 'active',
    company_id: 'comp-101',
    phone: '+91 98110 33442',
    created_at: '2026-02-01T09:30:00Z',
    last_login_at: '2026-09-24T16:20:00Z',
    email_verified: true,
    password: 'password123',
  },
  {
    id: 'usr-3',
    email: 'rohit.verma@zenithapex.in',
    full_name: 'Rohit Verma (Sales Executive)',
    role: 'Sales Staff',
    permissions: [
      'view_dashboard',
      'view_sales', 'create_sales', 'edit_sales',
      'manage_challans',
      'view_customers', 'create_customers',
    ],
    status: 'active',
    company_id: 'comp-101',
    phone: '+91 99220 55667',
    created_at: '2026-03-10T11:15:00Z',
    last_login_at: '2026-09-25T08:10:00Z',
    email_verified: true,
    password: 'password123',
  },
  {
    id: 'usr-4',
    email: 'kavita.nair@zenithapex.in',
    full_name: 'Kavita Nair (Inventory Manager)',
    role: 'Inventory Staff',
    permissions: [
      'view_dashboard',
      'view_products', 'create_products', 'edit_products',
      'manage_inventory',
    ],
    status: 'active',
    company_id: 'comp-101',
    phone: '+91 97400 66778',
    created_at: '2026-03-15T14:00:00Z',
    last_login_at: '2026-09-25T10:05:00Z',
    email_verified: true,
    password: 'password123',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    company_id: 'comp-101',
    sku: 'ZEN-SVR-X1',
    name: 'Enterprise Rackmount Server Chassis 2U',
    description: 'High-density 2U industrial rackmount server chassis with dual redundant 800W power supply units',
    category: 'Server Hardware',
    subcategory: 'Chassis',
    brand: 'Zenith Industrial',
    hsn_sac_code: '84715000',
    barcode: '8901234567890',
    unit: 'Units',
    purchase_price: 38500,
    selling_price: 52000,
    mrp: 58000,
    discount_percent: 5,
    gst_rate: 18,
    opening_stock: 45,
    min_stock: 10,
    max_stock: 120,
    current_stock: 38,
    warehouse_id: 'wh-1',
    rack: 'A-02-04',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-2',
    company_id: 'comp-101',
    sku: 'ZEN-NET-SW48',
    name: 'Managed 48-Port L3 Gigabit PoE+ Switch',
    description: 'Enterprise layer 3 switch with 48 PoE+ GbE ports, 4x 10G SFP+ uplinks, 740W PoE budget',
    category: 'Networking',
    subcategory: 'Managed Switches',
    brand: 'Zenith NetEdge',
    hsn_sac_code: '85176290',
    barcode: '8901234567891',
    unit: 'Units',
    purchase_price: 24500,
    selling_price: 34000,
    mrp: 38500,
    discount_percent: 0,
    gst_rate: 18,
    opening_stock: 60,
    min_stock: 15,
    max_stock: 150,
    current_stock: 52,
    warehouse_id: 'wh-1',
    rack: 'B-01-02',
    image_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=500&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-01-20T10:00:00Z',
  },
  {
    id: 'prod-3',
    company_id: 'comp-101',
    sku: 'ZEN-RAM-DDR5-32',
    name: 'ECC Registered DDR5 4800MHz 32GB RAM',
    description: 'Server grade ECC RDIMM module with on-die error correction for enterprise virtualization',
    category: 'Memory & Storage',
    subcategory: 'Server RAM',
    brand: 'HyperCore',
    hsn_sac_code: '84733020',
    barcode: '8901234567892',
    unit: 'Units',
    purchase_price: 8200,
    selling_price: 11800,
    mrp: 13500,
    discount_percent: 0,
    gst_rate: 18,
    opening_stock: 150,
    min_stock: 25,
    max_stock: 400,
    current_stock: 114,
    warehouse_id: 'wh-1',
    rack: 'C-04-01',
    image_url: 'https://images.unsplash.com/photo-1562976540-1502c2145186?w=500&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-02-05T10:00:00Z',
  },
  {
    id: 'prod-4',
    company_id: 'comp-101',
    sku: 'ZEN-NVME-2TB',
    name: 'Enterprise PCIe Gen4 2TB NVMe SSD U.2',
    description: 'High-endurance 3 DWPD enterprise SSD for mission-critical database IOPS',
    category: 'Memory & Storage',
    subcategory: 'Enterprise SSD',
    brand: 'SolidState Pro',
    hsn_sac_code: '84717020',
    barcode: '8901234567893',
    unit: 'Units',
    purchase_price: 14200,
    selling_price: 19800,
    mrp: 22000,
    discount_percent: 2,
    gst_rate: 18,
    opening_stock: 80,
    min_stock: 20,
    max_stock: 200,
    current_stock: 12, // Low stock trigger!
    warehouse_id: 'wh-2',
    rack: 'C-02-05',
    image_url: 'https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=500&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-02-10T10:00:00Z',
  },
  {
    id: 'prod-5',
    company_id: 'comp-101',
    sku: 'ZEN-UPS-3KVA',
    name: 'Online Double-Conversion 3kVA Pure Sine UPS',
    description: 'Industrial rackmount/tower UPS with zero transfer time and extended battery bank support',
    category: 'Power Management',
    subcategory: 'Online UPS',
    brand: 'VoltShield',
    hsn_sac_code: '85044090',
    barcode: '8901234567894',
    unit: 'Units',
    purchase_price: 42000,
    selling_price: 56500,
    mrp: 62000,
    discount_percent: 5,
    gst_rate: 18,
    opening_stock: 20,
    min_stock: 5,
    max_stock: 50,
    current_stock: 4, // Low stock trigger!
    warehouse_id: 'wh-3',
    rack: 'D-01-01',
    image_url: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?w=500&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-02-15T10:00:00Z',
  },
  {
    id: 'prod-6',
    company_id: 'comp-101',
    sku: 'ZEN-FIBER-OM4',
    name: '100m LC-LC Duplex OM4 Multimode Fiber Cable',
    description: 'Armored 50/125um LSZH plenum-rated fiber optic patch cable for high-speed SAN interconnects',
    category: 'Cabling & SAN',
    subcategory: 'Optical Fiber',
    brand: 'OptiLink',
    hsn_sac_code: '85447090',
    barcode: '8901234567895',
    unit: 'Rolls',
    purchase_price: 2400,
    selling_price: 3600,
    mrp: 4200,
    discount_percent: 0,
    gst_rate: 18,
    opening_stock: 120,
    min_stock: 30,
    max_stock: 300,
    current_stock: 88,
    warehouse_id: 'wh-1',
    rack: 'E-03-02',
    image_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=80',
    status: 'active',
    created_at: '2026-03-01T10:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust-1',
    company_id: 'comp-101',
    name: 'Arjun Nambiar',
    company_name: 'CloudScale Infra Solutions LLP',
    phone: '+91 98451 22334',
    email: 'procurement@cloudscale.io',
    address: 'Tower B, 7th Floor, RMZ Infinity, Old Madras Road',
    city: 'Bengaluru',
    state: 'Karnataka',
    pin_code: '560016',
    gstin: '29AAAFC1234A1Z1',
    pan: 'AAAFC1234A',
    credit_limit: 500000,
    opening_balance: 45000,
    current_balance: 148500,
    payment_terms: 'Net 30',
    customer_type: 'Corporate',
    status: 'active',
    created_at: '2026-01-18T10:00:00Z',
  },
  {
    id: 'cust-2',
    company_id: 'comp-101',
    name: 'Rajesh Singhania',
    company_name: 'Metro Networks & Telecom Pvt Ltd',
    phone: '+91 98201 33445',
    email: 'billing@metronetworks.in',
    address: 'Unit 302, Nesco IT Park, Western Express Highway, Goregaon',
    city: 'Mumbai',
    state: 'Maharashtra', // Inter-state!
    pin_code: '400063',
    gstin: '27AABCM5678B1Z4',
    pan: 'AABCM5678B',
    credit_limit: 800000,
    opening_balance: 0,
    current_balance: 82500,
    payment_terms: 'Net 15',
    customer_type: 'Wholesale',
    status: 'active',
    created_at: '2026-02-02T10:00:00Z',
  },
  {
    id: 'cust-3',
    company_id: 'comp-101',
    name: 'Sunil Aggarwal',
    company_name: 'CyberFortress Systems India',
    phone: '+91 98112 44556',
    email: 'accounts@cyberfortress.com',
    address: 'DLF Cyber City, Building 10, DLF Phase 2',
    city: 'Gurugram',
    state: 'Haryana', // Inter-state!
    pin_code: '122002',
    gstin: '06AACCC9876C1Z8',
    pan: 'AACCC9876C',
    credit_limit: 1200000,
    opening_balance: 15000,
    current_balance: 245000,
    payment_terms: 'Net 45',
    customer_type: 'Distributor',
    status: 'active',
    created_at: '2026-02-12T10:00:00Z',
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'supp-1',
    company_id: 'comp-101',
    name: 'Manish Parekh',
    company_name: 'Apex Semiconductor Distributors India',
    phone: '+91 98205 66778',
    email: 'orders@apexsemicon.in',
    address: 'Plot 104, MIDC Industrial Area, Andheri East',
    city: 'Mumbai',
    state: 'Maharashtra',
    gstin: '27AAACP9988D1Z2',
    pan: 'AAACP9988D',
    opening_balance: 80000,
    current_balance: 165000,
    payment_terms: 'Net 30',
    bank_details: 'ICICI Bank, A/C: 001105009988, IFSC: ICIC0000011',
    status: 'active',
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'supp-2',
    company_id: 'comp-101',
    name: 'Girish Hegde',
    company_name: 'Kaveri Industrial Power Components',
    phone: '+91 98452 77889',
    email: 'sales@kaveripower.co.in',
    address: '22/B, Industrial Suburb, Yeshwanthpur',
    city: 'Bengaluru',
    state: 'Karnataka',
    gstin: '29AABCK3344E1Z7',
    pan: 'AABCK3344E',
    opening_balance: 0,
    current_balance: 42000,
    payment_terms: 'Net 15',
    bank_details: 'State Bank of India, A/C: 3899221100, IFSC: SBIN0004567',
    status: 'active',
    created_at: '2026-01-25T10:00:00Z',
  },
];

export const INITIAL_INVOICES: SalesInvoice[] = [
  {
    id: 'inv-1',
    company_id: 'comp-101',
    invoice_number: 'INV-2627-001',
    invoice_date: '2026-09-18',
    due_date: '2026-10-18',
    customer_id: 'cust-1',
    customer_name: 'CloudScale Infra Solutions LLP',
    customer_gstin: '29AAAFC1234A1Z1',
    customer_state: 'Karnataka',
    customer_phone: '+91 98451 22334',
    billing_address: 'Tower B, 7th Floor, RMZ Infinity, Old Madras Road, Bengaluru - 560016',
    shipping_address: 'Tower B, 7th Floor, RMZ Infinity, Old Madras Road, Bengaluru - 560016',
    items: [
      {
        id: 'item-1',
        product_id: 'prod-1',
        product_name: 'Enterprise Rackmount Server Chassis 2U',
        hsn_code: '84715000',
        unit: 'Units',
        quantity: 2,
        rate: 52000,
        discount_percent: 5,
        discount_amount: 5200,
        taxable_amount: 98800,
        gst_rate: 18,
        cgst_amount: 8892,
        sgst_amount: 8892,
        igst_amount: 0,
        total: 116584,
      },
      {
        id: 'item-2',
        product_id: 'prod-3',
        product_name: 'ECC Registered DDR5 4800MHz 32GB RAM',
        hsn_code: '84733020',
        unit: 'Units',
        quantity: 4,
        rate: 11800,
        discount_percent: 0,
        discount_amount: 0,
        taxable_amount: 47200,
        gst_rate: 18,
        cgst_amount: 4248,
        sgst_amount: 4248,
        igst_amount: 0,
        total: 55696,
      },
    ],
    subtotal: 151200,
    total_discount: 5200,
    taxable_amount: 146000,
    total_cgst: 13140,
    total_sgst: 13140,
    total_igst: 0,
    round_off: 0,
    grand_total: 172280,
    paid_amount: 100000,
    balance_due: 72280,
    payment_status: 'Partially Paid',
    payment_method: 'Bank Transfer',
    notes: 'Payment terms: 30 days. All server chassis include 3-year OEM on-site warranty.',
    terms_and_conditions: '1. Goods once sold will be accepted back only in original sealed packaging.\n2. Interest @ 18% p.a. will be charged if payment is delayed beyond due date.\n3. Subject to Bengaluru jurisdiction.',
    warehouse_id: 'wh-1',
    created_by: 'Vikram Kumar',
    created_at: '2026-09-18T11:30:00Z',
  },
  {
    id: 'inv-2',
    company_id: 'comp-101',
    invoice_number: 'INV-2627-002',
    invoice_date: '2026-09-22',
    due_date: '2026-10-07',
    customer_id: 'cust-2',
    customer_name: 'Metro Networks & Telecom Pvt Ltd',
    customer_gstin: '27AABCM5678B1Z4',
    customer_state: 'Maharashtra', // Inter-state IGST
    customer_phone: '+91 98201 33445',
    billing_address: 'Unit 302, Nesco IT Park, Western Express Highway, Goregaon, Mumbai - 400063',
    shipping_address: 'Goregaon Data Center Annex, Western Express Highway, Mumbai - 400063',
    items: [
      {
        id: 'item-3',
        product_id: 'prod-2',
        product_name: 'Managed 48-Port L3 Gigabit PoE+ Switch',
        hsn_code: '85176290',
        unit: 'Units',
        quantity: 2,
        rate: 34000,
        discount_percent: 0,
        discount_amount: 0,
        taxable_amount: 68000,
        gst_rate: 18,
        cgst_amount: 0,
        sgst_amount: 0,
        igst_amount: 12240,
        total: 80240,
      },
    ],
    subtotal: 68000,
    total_discount: 0,
    taxable_amount: 68000,
    total_cgst: 0,
    total_sgst: 0,
    total_igst: 12240,
    round_off: 0,
    grand_total: 80240,
    paid_amount: 80240,
    balance_due: 0,
    payment_status: 'Paid',
    payment_method: 'UPI',
    notes: 'Inter-state B2B supply against GST e-Way Bill generated.',
    terms_and_conditions: 'Subject to Bengaluru jurisdiction. Standard manufacturer warranty applies.',
    warehouse_id: 'wh-1',
    created_by: 'Rohit Verma',
    created_at: '2026-09-22T14:10:00Z',
  },
];

export const INITIAL_CHALLANS: DeliveryChallan[] = [
  {
    id: 'dc-1',
    company_id: 'comp-101',
    challan_number: 'DC-2627-001',
    challan_date: '2026-09-20',
    customer_id: 'cust-1',
    customer_name: 'CloudScale Infra Solutions LLP',
    delivery_address: 'Data Center Suite 3, Ground Floor, Electronic City, Bengaluru',
    reference_invoice_number: 'INV-2627-001',
    reference_invoice_id: 'inv-1',
    transporter: 'V-Trans Logistics India Ltd',
    vehicle_number: 'KA-01-MJ-4412',
    eway_bill_number: '291088746251',
    items: [
      {
        id: 'dci-1',
        product_id: 'prod-1',
        product_name: 'Enterprise Rackmount Server Chassis 2U',
        hsn_code: '84715000',
        unit: 'Units',
        quantity: 2,
        rate: 52000,
        notes: 'Chassis serial nos: SN-26-8801, SN-26-8802',
      },
      {
        id: 'dci-2',
        product_id: 'prod-3',
        product_name: 'ECC Registered DDR5 4800MHz 32GB RAM',
        hsn_code: '84733020',
        unit: 'Units',
        quantity: 4,
        rate: 11800,
        notes: 'Sealed ESD antistatic packs',
      },
    ],
    status: 'Converted',
    converted_invoice_id: 'inv-1',
    received_by: 'Suresh Nayak (Site Supervisor)',
    remarks: 'Delivered in pristine condition with safety seals intact.',
    warehouse_id: 'wh-1',
    created_by: 'Rohit Verma',
    created_at: '2026-09-20T09:45:00Z',
  },
  {
    id: 'dc-2',
    company_id: 'comp-101',
    challan_number: 'DC-2627-002',
    challan_date: '2026-09-24',
    customer_id: 'cust-3',
    customer_name: 'CyberFortress Systems India',
    delivery_address: 'Building 10, DLF Cyber City, Gurugram, Haryana - 122002',
    reference_invoice_number: '',
    transporter: 'BlueDart Express Cargo',
    vehicle_number: 'HR-55-AF-9021',
    eway_bill_number: '061099234812',
    items: [
      {
        id: 'dci-3',
        product_id: 'prod-6',
        product_name: '100m LC-LC Duplex OM4 Multimode Fiber Cable',
        hsn_code: '85447090',
        unit: 'Rolls',
        quantity: 10,
        rate: 3600,
        notes: 'For pre-commissioning testing and cabling certification',
      },
    ],
    status: 'Pending', // Pending conversion to invoice
    received_by: 'Awaiting Delivery Confirmation',
    remarks: 'Goods dispatched for client site inspection and acceptance trial.',
    warehouse_id: 'wh-3',
    created_by: 'Kavita Nair',
    created_at: '2026-09-24T16:00:00Z',
  },
];

export const INITIAL_PURCHASES: PurchaseInvoice[] = [
  {
    id: 'po-1',
    company_id: 'comp-101',
    purchase_number: 'PO-2627-001',
    supplier_invoice_no: 'APEX/26/8941',
    purchase_date: '2026-09-12',
    due_date: '2026-10-12',
    supplier_id: 'supp-1',
    supplier_name: 'Apex Semiconductor Distributors India',
    supplier_gstin: '27AAACP9988D1Z2',
    items: [
      {
        id: 'pi-1',
        product_id: 'prod-3',
        product_name: 'ECC Registered DDR5 4800MHz 32GB RAM',
        unit: 'Units',
        quantity: 20,
        rate: 8200,
        discount_percent: 0,
        taxable_amount: 164000,
        gst_rate: 18,
        gst_amount: 29520,
        total: 193520,
      },
    ],
    subtotal: 164000,
    total_discount: 0,
    total_gst: 29520,
    round_off: 0,
    grand_total: 193520,
    paid_amount: 100000,
    balance_due: 93520,
    payment_status: 'Partially Paid',
    payment_method: 'Bank Transfer',
    warehouse_id: 'wh-1',
    notes: 'Batch consignment with manufacturer warranty certificate',
    created_by: 'Vikram Kumar',
    created_at: '2026-09-12T10:00:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    company_id: 'comp-101',
    payment_number: 'RCPT-26-001',
    date: '2026-09-19',
    party_type: 'Customer',
    party_id: 'cust-1',
    party_name: 'CloudScale Infra Solutions LLP',
    payment_type: 'Receipt',
    amount: 100000,
    payment_method: 'Bank Transfer',
    reference_number: 'NEFT/HDFC/20260919/88219',
    invoice_id: 'inv-1',
    notes: 'Advance installment against INV-2627-001',
    created_by: 'Priya Sharma',
    created_at: '2026-09-19T14:30:00Z',
  },
  {
    id: 'pay-2',
    company_id: 'comp-101',
    payment_number: 'RCPT-26-002',
    date: '2026-09-22',
    party_type: 'Customer',
    party_id: 'cust-2',
    party_name: 'Metro Networks & Telecom Pvt Ltd',
    payment_type: 'Receipt',
    amount: 80240,
    payment_method: 'UPI',
    reference_number: 'UPI/628819201928@icici',
    invoice_id: 'inv-2',
    notes: 'Full payment cleared for INV-2627-002',
    created_by: 'Rohit Verma',
    created_at: '2026-09-22T14:15:00Z',
  },
  {
    id: 'pay-3',
    company_id: 'comp-101',
    payment_number: 'PMT-26-001',
    date: '2026-09-15',
    party_type: 'Supplier',
    party_id: 'supp-1',
    party_name: 'Apex Semiconductor Distributors India',
    payment_type: 'Payment',
    amount: 100000,
    payment_method: 'Bank Transfer',
    reference_number: 'RTGS/HDFC/20260915/10291',
    notes: 'Part settlement for PO-2627-001',
    created_by: 'Priya Sharma',
    created_at: '2026-09-15T11:00:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    company_id: 'comp-101',
    expense_number: 'EXP-26-001',
    date: '2026-09-05',
    category: 'Rent',
    description: 'Monthly warehouse and office premises lease for Electronic City',
    amount: 75000,
    tax_amount: 13500,
    total_amount: 88500,
    payment_method: 'Bank Transfer',
    vendor_name: 'Prestige Estates Commercial Leases Ltd',
    notes: 'TDS deducted @ 10% u/s 194-I',
    created_by: 'Priya Sharma',
    created_at: '2026-09-05T10:00:00Z',
  },
  {
    id: 'exp-2',
    company_id: 'comp-101',
    expense_number: 'EXP-26-002',
    date: '2026-09-10',
    category: 'Electricity',
    description: 'BESCOM commercial high-tension industrial power utility bill',
    amount: 22400,
    tax_amount: 0,
    total_amount: 22400,
    payment_method: 'Bank Transfer',
    vendor_name: 'Bangalore Electricity Supply Company Limited',
    notes: 'Consumer ID: 883921004',
    created_by: 'Priya Sharma',
    created_at: '2026-09-10T12:00:00Z',
  },
  {
    id: 'exp-3',
    company_id: 'comp-101',
    expense_number: 'EXP-26-003',
    date: '2026-09-18',
    category: 'Transport',
    description: 'Freight charges for inter-warehouse container transit',
    amount: 14500,
    tax_amount: 725,
    total_amount: 15225,
    payment_method: 'UPI',
    vendor_name: 'V-Trans Express Transport Logistics',
    notes: 'Docket # VT-99210',
    created_by: 'Kavita Nair',
    created_at: '2026-09-18T16:00:00Z',
  },
];

export const INITIAL_TRANSACTIONS: InventoryTransaction[] = [
  {
    id: 'tx-1',
    company_id: 'comp-101',
    product_id: 'prod-3',
    product_name: 'ECC Registered DDR5 4800MHz 32GB RAM',
    warehouse_id: 'wh-1',
    warehouse_name: 'Central Distribution Center (BLR)',
    transaction_type: 'Purchase',
    quantity: 20,
    previous_stock: 98,
    new_stock: 118,
    reference_type: 'Purchase',
    reference_id: 'po-1',
    reference_number: 'PO-2627-001',
    notes: 'Stock received via supplier invoice APEX/26/8941',
    created_by_name: 'Vikram Kumar',
    created_at: '2026-09-12T10:15:00Z',
  },
  {
    id: 'tx-2',
    company_id: 'comp-101',
    product_id: 'prod-1',
    product_name: 'Enterprise Rackmount Server Chassis 2U',
    warehouse_id: 'wh-1',
    warehouse_name: 'Central Distribution Center (BLR)',
    transaction_type: 'Sales',
    quantity: -2,
    previous_stock: 40,
    new_stock: 38,
    reference_type: 'Invoice',
    reference_id: 'inv-1',
    reference_number: 'INV-2627-001',
    notes: 'Dispatched for CloudScale Infra Solutions LLP',
    created_by_name: 'Rohit Verma',
    created_at: '2026-09-18T11:35:00Z',
  },
  {
    id: 'tx-3',
    company_id: 'comp-101',
    product_id: 'prod-3',
    product_name: 'ECC Registered DDR5 4800MHz 32GB RAM',
    warehouse_id: 'wh-1',
    warehouse_name: 'Central Distribution Center (BLR)',
    transaction_type: 'Sales',
    quantity: -4,
    previous_stock: 118,
    new_stock: 114,
    reference_type: 'Invoice',
    reference_id: 'inv-1',
    reference_number: 'INV-2627-001',
    notes: 'Dispatched for CloudScale Infra Solutions LLP',
    created_by_name: 'Rohit Verma',
    created_at: '2026-09-18T11:35:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'audit-1',
    company_id: 'comp-101',
    user_name: 'Vikram Kumar',
    user_email: 'vikram.admin@zenithapex.in',
    action: 'Login',
    module: 'Auth',
    record_id: 'usr-1',
    details: 'User authenticated successfully via secure session.',
    ip_address: '192.168.1.104',
    created_at: '2026-09-25T11:45:00Z',
  },
  {
    id: 'audit-2',
    company_id: 'comp-101',
    user_name: 'Rohit Verma',
    user_email: 'rohit.verma@zenithapex.in',
    action: 'Create',
    module: 'Sales',
    record_id: 'inv-2',
    details: 'Generated Tax Invoice INV-2627-002 for Metro Networks (₹80,240.00).',
    ip_address: '192.168.1.112',
    created_at: '2026-09-22T14:10:00Z',
  },
  {
    id: 'audit-3',
    company_id: 'comp-101',
    user_name: 'Kavita Nair',
    user_email: 'kavita.nair@zenithapex.in',
    action: 'Create',
    module: 'Challans',
    record_id: 'dc-2',
    details: 'Created Delivery Challan DC-2627-002 with e-Way Bill 061099234812.',
    ip_address: '192.168.1.118',
    created_at: '2026-09-24T16:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    company_id: 'comp-101',
    title: 'Low Stock Alert: NVMe SSD 2TB',
    message: 'Current stock of Enterprise PCIe Gen4 2TB NVMe SSD has dropped to 12 units (Minimum threshold: 20 units).',
    type: 'warning',
    read: false,
    link: 'inventory',
    created_at: '2026-09-25T08:00:00Z',
  },
  {
    id: 'notif-2',
    company_id: 'comp-101',
    title: 'Low Stock Alert: Online 3kVA UPS',
    message: 'Current stock of Online 3kVA Pure Sine UPS is 4 units (Minimum threshold: 5 units). Reorder recommended.',
    type: 'warning',
    read: false,
    link: 'inventory',
    created_at: '2026-09-25T08:30:00Z',
  },
  {
    id: 'notif-3',
    company_id: 'comp-101',
    title: 'Payment Received: ₹80,240.00',
    message: 'Metro Networks & Telecom Pvt Ltd settled full invoice balance for INV-2627-002 via UPI.',
    type: 'success',
    read: true,
    link: 'payments',
    created_at: '2026-09-22T14:15:00Z',
  },
];
